version: '3'

services:
  db:
    image: postgres:12
    environment:
      POSTGRES_DB: indicium-northwind
      POSTGRES_USER: northwind_user
      POSTGRES_PASSWORD: thewindisblowing
    volumes:
      - ./dbdata:/var/lib/postgresql/data
      - ./northwind.sql:/docker-entrypoint-initdb.d/northwind.sql
    container_name: "indicium-northwind"
    ports:
      - 5434:5432